#!/bin/bash -l

##OVERVIEW for WEEK 5 ASSIGNMENT - mtDNA Mapping:
#For this assignment, we will be mapping our trimmed sequences to the mtDNA reference genomes (rCRS), which is a 3-step process:
#1. We first have to do the actual mapping using bwa 
#2. Then we use samtools to filter the mapped reads to a certain quality. We also use samtools to merge reads from multiple lanes or sequencing runs
#3. Finally, we run mapping statistics using qualimap to determine coverage

##We will run each step on one set of paired-end reads using an interactive session, then use a script with a loop to run all samples

#The trimmed sequences should be in your ../Data/2_AdapterRemoval/FINISHED directory
#If you have not trimmed the adapters yet, please go back to Week 3 and/or 4 and run through the assignment there.

#######################
########PART 0########
######################
#housekeeping before we start the assignment!!! Keep a clean house!!!

#copy this script into your own USER directory. Type the following into the terminal:
USER="Lucy" #replace Lucy with your actual foldername
cp /dartfs/rc/lab/F/FleskesR/BioinfoWG/ASSIGNMENTS/WEEK5-MappingMTDNA/5_MappingMTDNA_assignment.sh /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Scripts/
#then modify the script in your own folder


######################
########PART 1########
######################
##Mapping one sample to the Revised Cambridge Reference Sequence (rCRS) of human mitochondrial DNA (mtDNA)

#We start an interactive session as before:
srun --pty bash -l
#Then activate the conda environment for mapping
conda activate Sequencing


##Step 1: set up folders and variables
USER="Lucy" #replace Lucy with your actual foldername
mkdir -p /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/{mapped,qualimap}

cd /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA

#Make variable with trimmed sequences in it (after you have run AdapterRemoval and any other adapter-trimming tools):
PATH_TRIMMED=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/2_AdapterRemoval/FINISHED
#Make variable for mapped and qualimap steps' paths
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/mapped
PATH_QUALI=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/qualimap
#Finally, make a variable for the folder where the rCRS lives:
PATH_REF=/dartfs/rc/lab/F/FleskesR/ReferenceSeqs/MtDNA


##Step 2: Explore rCRS
#Look at the >16,000 bases of the rCRS human mtDNA sequence (!!IMPORTANT: DO NOT EDIT THIS FILE!!)
less /dartfs/rc/lab/F/FleskesR/ReferenceSeqs/MtDNA/rCRS.fasta 
#exit back to the terminal by pressing q

#Question 1: How are fasta files set up? The Fasta file tells us the name of the sequence (after the >) and then the sequence/bases itself. 
#Question 2: How are fasta files different from the fastq files we've been working with (you may need to do additional research for this)? 
#Fasta files only have the sequence information and the name of the sequence, while fastq files also have quality information for each base. 
#Fasta files are used for reference sequences, while fastq files are used for raw sequencing reads from high-throughput sequencing technologies like Illumina.
#Fasta files have a simple format with a header line starting with ">" followed by the sequence name, and then the sequence itself on the following lines. Fastq files have a more complex format with four lines per sequence: the header line starting with "@", the sequence line, a "+" line, and a quality score line.
#https://sequenceserver.com/blog/fasta-vs-fastq-formats/


##Step 3: Run bwa mem mapping to rCRS
#Note: If you use this script outside of class on your own computer, you will need to do something called "indexing" the reference sequence/genome for bwa to work. See: https://bio-bwa.sourceforge.net/bwa.shtml.
#We will be using the "mem" algorithm for mapping our sequences to the rCRS. There is also the "aln" algorithm, but it requires more time and the use of other options.
#Replace CAL05_FGC2096_s_1.R1.fastq.truncated with your sequence file name in the 2_AdapterRemoval/FINISHED folder (we are only using the "truncated" files!)
#bwa mem -t 2 $PATH_REF/rCRS.fasta $PATH_TRIMMED/CAL05_FGC2096_s_1.R1.fastq.truncated.gz > $PATH_MAP/CAL05_FGC2096_s_1.R1.mtDNA.mem.sam
bwa mem -t 2 $PATH_REF/rCRS.fasta $PATH_TRIMMED/CAL03_FGC2098_s_1_CGGCTATG-CCTATCCT.fastq.truncated.gz > $PATH_MAP/CAL03_FGC2098_s_1_CGGCTATG-CCTATCCT.mtDNA.mem.sam

#Check if it worked. You should have a *.sam file in your PATH_MAP. Use cd and ls to go to the bwa folder to check.
#Use the less command again to explore the sam file (use q to exit back to the terminal)

#Question 3: Paste the first three lines of the sam file below.
#@SQ     SN:rCRS LN:16569
#@HD     VN:1.5  SO:unsorted     GO:query
#@PG     ID:bwa  PN:bwa  VN:0.7.18-r1243-dirty   CL:bwa mem -t 2 /dartfs/rc/lab/F/FleskesR/ReferenceSeqs/MtDNA/rCRS.fasta /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/Lucy/Data/2_AdapterRemoval/FINISHED/CAL03_FGC2098_s_1_CGGCTATG-CCTATCCT.fastq.truncated.gz

#Question 4: What does the @SQ line mean? The @HD line? The @PG line?
#The @SQ line provides information about the reference sequence, including its name (SN) and length (LN). In this case, it indicates that the reference sequence is "rCRS" and its length is 16569 bases.
#SQ stands for "Sequence Dictionary" and it describes the reference sequences used in the alignment/stores information about the reference sequences against which the reads are aligned. In this case, it indicates that the reference sequence is "rCRS" and its length is 16569 bases.
#The @HD line provides information about the header of the SAM file, including the version of the SAM format (VN), the sorting order of the alignments (SO), and the grouping of the alignments (GO). In this case, it indicates that the SAM file is in version 1.5, the alignments are unsorted, and they are grouped by query.
#The @PG line provides information about the program used to generate the SAM file, including its name (PN), version (VN), and command line (CL).
#https://learn.gencore.bio.nyu.edu/ngs-file-formats/sambam-format/

#Following the header lines (the first three lines from the above questions) is the sequence alignment information. 
#i.e., where each sequence aligns to the genome, and how probable it fits there.



######################
########PART 2########
######################
#We now need to filter out the sequence reads that do not match to the rCRS.
#The sam file we generated with bwa has ALL of the reads in it, whether they match the rCRS or not. 
#We use the program samtools to filter the reads that we want to keep. Later, we will also use samtools to merge multiple sequences from one individual into a single file.

#If you have paused and logged off between Part 1 and Part 2,
#Make sure you are still in an interactive session with the Sequencing conda environment activated before moving on.
#And that you have defined your variables again.

cd $PATH_MAP

#One more variable to define, the name of your sam file:
NAME="CAL03_FGC2098_s_1_CGGCTATG-CCTATCCT" #change to your file name before .sam

#Step 1: Convert from sam to bam file (bam is the binary version of sam; helpful for big files)
samtools view -bSh -@ 2 ${NAME}.mtDNA.mem.sam > ${NAME}.mtDNA.mem.bam
#Run the code below to determine how many reads are present before filtering:
samtools view -c ${NAME}.mtDNA.mem.bam
#Question 5: How many reads are we starting with? 3398667

#Step 2: Filter out mapped reads 
samtools view -bh -F 4 -@ 2 ${NAME}.mtDNA.mem.bam > ${NAME}.mtDNA.mem.mapped.bam
#Question 6: Using the same samtools view -c code as above, find how many reads we have now (Hint: You will have to change the file name if you copy the code from above). 
samtools view -c ${NAME}.mtDNA.mem.mapped.bam
#Question 6: How many reads do we have now? 13540

#Step 3: Filter by q30 quality
samtools view -bh -q 30 ${NAME}.mtDNA.mem.mapped.bam > ${NAME}.mtDNA.mem.mapped.q30.bam
samtools view -c ${NAME}.mtDNA.mem.mapped.q30.bam
#Question 7: How many reads do we have now? 13528

#Step 4: Now we remove duplicates. First, we sort the reads by leftmost coordinate, then remove duplicates.
#Sorting alignment by leftmost coordinate
samtools sort -T ${NAME}.mtDNA.mem.mapped.q30.sort -o ${NAME}.mtDNA.mem.mapped.q30.sort.bam ${NAME}.mtDNA.mem.mapped.q30.bam
#Removing duplicates
samtools rmdup -s ${NAME}.mtDNA.mem.mapped.q30.sort.bam ${NAME}.mtDNA.mem.mapped.q30.sort.rmdup.bam
#Removing reads with multiple mappings
samtools view -bh -F 0x900 ${NAME}.mtDNA.mem.mapped.q30.sort.rmdup.bam > ${NAME}.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam
#Question 8: Now how many unique mapped reads with a quality of at least 30 do we have? (Hint: You'll want to look at the final file produced above)
samtools view -c ${NAME}.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam
# We have 9087 unique mapped reads with a quality of at least 30.

##We do not need all of the intermediary files we just created.
#We create them in case there is an error, to check where it happened, but once everything is completed, 
#we delete everything but the first, unfiltered bam file and the last *.uniq.bam files (delete the sam file too, as it is the same as the first bam, it just takes up more space)

rm ${NAME}.mtDNA.mem.mapped.bam
rm ${NAME}.mtDNA.mem.mapped.q30.bam
rm ${NAME}.mtDNA.mem.mapped.q30.sort.bam
rm ${NAME}.mtDNA.mem.mapped.q30.sort.rmdup.bam
rm ${NAME}.mtDNA.mem.sam

#exit the interactive session:
exit 


######################
########PART 3########
######################
#Now, we want to understand what each of the flags we used in samtools did. 
#Using the samtools manual (https://www.htslib.org/doc/samtools.html), give a short definition for the following flags for the programs "view," "sort", and "rmdup":

#For samtools view:
# -b
#write your answer here: Output in BAM format. By default, samtools view outputs in SAM format, which is a human-readable text format. The -b flag tells samtools to output in BAM format, which is a binary format that is more compact and faster to process than SAM.

# -S
#write your answer here: Input is in SAM format. By default, samtools view expects input in BAM format. The -S flag tells samtools that the input is in SAM format, which is a human-readable text format. This flag is necessary when the input file has a .sam extension, as samtools will not automatically detect the format based on the file extension.

# -h 
#write your answer here: Include the header in the output. By default, samtools view does not include the header lines (lines starting with @) in the output when filtering or converting SAM/BAM files. The -h flag tells samtools to include the header lines in the output, which can be important for downstream analysis and for maintaining information about the reference sequences and alignment parameters used in the original SAM/BAM file.

# -@
#write your answer here: Sets the number of threads to use for compression. This can speed up the processing of large SAM/BAM files by allowing samtools to utilize multiple CPU cores. For example, -@ 2 would use 2 threads for processing.

# -F 
#write your answer here: Exclude reads with the specified flag(s). This is useful for filtering out reads that meet certain criteria, such as unmapped reads (flag 0x4) or secondary alignments (flag 0x100).

# -q 
#write your answer here: Filter reads by quality. This is useful for removing reads with low mapping quality, which may indicate poor alignments. The value specified with -q is the minimum mapping quality score required for a read to be included in the output. For example, -q 30 would only include reads with a mapping quality score of 30 or higher.

# -c 
#write your answer here: Counts and print the total number of alignments in the input. This is useful for quickly determining the number of reads in a BAM file without having to convert it to SAM format and count the lines.

#For samtools sort:
# -T
#write your answer here: Specify the prefix for temporary files used during sorting. When samtools sort processes a BAM file, it may need to create temporary files to hold intermediate data. The -T flag allows you to specify a prefix for these temporary files, which can help with organization and cleanup after the sorting process is complete. For example, -T sorted_temp would create temporary files with names starting with "sorted_temp".

#For samtools rmdup 
# -S
#write your answer here: Remove duplicates from single-end reads. By default, samtools rmdup is designed for paired-end reads and will look for duplicate pairs of reads. The -S flag tells samtools to treat the input as single-end reads, which means it will look for duplicate individual reads rather than pairs. This is important when working with single-end sequencing data, as the criteria for identifying duplicates may differ from those used for paired-end data.

#Question 9: What if we wanted to filter for unmapped reads only? We will have to check the samtools view command and specific flags to do this.
#Unmapped reads are useful if you're mapping to the full human reference genome and you want to study pathogens in the ancient DNA. 
#What samtools code would you use to keep unmapped reads only?
#samtools view -bh -f 4 -@ 2 ${NAME}.mtDNA.mem.bam > ${NAME}.mtDNA.mem.unmapped.bam


######################
########PART 4########
######################
#Now, we will run bwa mapping and samtools filtering and merging on all of our samples using a slurm job 
#Instead of individually checking the read counts at each stage, this script will calculate them at the end and input into a text file.
#This script will also run Qualimap statistics. Find the manual for Qualimap online and be prepared to discuss the mapping statistics in class.

#Step 1: Copy the job script to your directory
USER="Lucy" #replace Lucy with your actual foldername
cp /dartfs/rc/lab/F/FleskesR/BioinfoWG/ASSIGNMENTS/WEEK5-MappingMTDNA/5_MappingMTDNA.sh /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Scripts/

cd /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Scripts/

#Edit variables and paths as needed in ../Scripts/5_MappingMTDNA.sh

#run 5_MappingMTDNALucy.sh
sbatch 5_MappingMTDNALucy.sh

#check status
squeue --me

#Once the job is completed, check the MappingFiltering statistics text file to confirm every sample worked.
#Then, clean up intermediary files and sam files:
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/mapped
cd $PATH_MAP

rm *.mtDNA.mem.mapped.q30.sort.rmdup.bam
rm *.mtDNA.mem.mapped.q30.sort.bam
rm *.mtDNA.mem.mapped.q30.bam
rm *.mtDNA.mem.mapped.bam
rm *.mtDNA.mem.sam

######################
########PART 5########
######################
#Now, we need to merge the unique sequencing reads into a single file. 
#We will use samtools merge command. Look at the manual to see how the "merge" program works.

#We start an interactive session as before:
srun --pty bash -l
#Then activate the conda environment for mapping
conda activate Sequencing

##Step 1: set up folders and variables
USER="Lucy" #replace Lucy with your actual foldername
SAMPLE="CAL03"
#change CAL## to your assigned sample

#Make variable for mapped pathss
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/mapped

cd $PATH_MAP

##Step 2: Merge files using samtools
#You will need to change the individual file names after the first line to match your file names. (Leave the first line as it is.)
#Use ls *.uniq.bam to get list of your file names.
#You will also need to add a backslash \ at the end of each line except for the last, 
#and each line after the first needs to be indented by one tab.

samtools merge -@ 2 ${SAMPLE}.mtDNA.mem.merged.bam \
    CAL03_FGC2096_s_1.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam \
    CAL03_FGC2098_s_1_CGGCTATG-CCTATCCT.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam \
    CAL03_FGC2098_s_2_CGGCTATG-CCTATCCT.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam \
    CAL03_FGC2098_s_3_CGGCTATG-CCTATCCT.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam \
    CAL03_FGC2098_s_4_CGGCTATG-CCTATCCT.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam \
    CAL03_FGC2099_s_1_CGGCTATG-CCTATCCT.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam \
    CAL03_FGC2099_s_2_CGGCTATG-CCTATCCT.mtDNA.mem.mapped.q30.sort.rmdup.uniq.bam 

##Step 3: Now we remove duplicates and reads that have multiple mappings. First, we sort the reads by leftmost coordinate, then remove duplicates.
#Sorting alignment by leftmost coordinate
samtools sort -T ${SAMPLE}.mtDNA.mem.merged.sort -o ${SAMPLE}.mtDNA.mem.merged.sort.bam ${SAMPLE}.mtDNA.mem.merged.bam
#Removing duplicates
samtools rmdup -s ${SAMPLE}.mtDNA.mem.merged.sort.bam ${SAMPLE}.mtDNA.mem.merged.sort.rmdup.bam
#Removing reads with multiple mappings
samtools view -bh -F 0x900 ${SAMPLE}.mtDNA.mem.merged.sort.rmdup.bam > ${SAMPLE}.mtDNA.mem.merged.sort.rmdup.uniq.bam
#Question 10: Now how many MERGED unique mapped reads with a quality of at least 30 do we have? (Hint: You'll want to look at the final file produced above)
samtools view -c ${SAMPLE}.mtDNA.mem.merged.sort.rmdup.uniq.bam
#We have 30213 merged unique mapped reads with a quality of at least 30.

#Finally, we create a new MergingStats file to keep this data:
echo -e "MAKE MERGING FILE"
echo -e "Sample \t Total Merged Reads \t Unique Merged Reads" > $PATH_MAP/MergingFilteringStats_${SAMPLE}_mtDNA.txt

merged=`samtools view -c $PATH_MAP/${SAMPLE}.mtDNA.mem.merged.bam`
uniq=`samtools view -c $PATH_MAP/${SAMPLE}.mtDNA.mem.merged.sort.rmdup.uniq.bam`

echo -e "${SAMPLE} \t $merged \t $uniq " >> $PATH_MAP/MergingFilteringStats_${SAMPLE}_mtDNA.txt

#Step 4: Clean up intermediary files
rm ${SAMPLE}.mtDNA.mem.merged.sort.bam
rm ${SAMPLE}.mtDNA.mem.merged.sort.rmdup.bam

######################
########PART 6########
######################
#Now that we have our final merged, unique reads mapped to the human mtDNA sequence rCRS, 
#We run statistics to get the coverage

#!!IMPORTANT: Make sure you are still in the interactive session!!
#If not, start a new interactive session, define your variables and paths, and activate the Sequencing conda environment.

#Make variable for mapped and qualimap steps' paths
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/mapped
PATH_QUALI=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/5_MappingMTDNA/qualimap

#Run Qualimap on the merged sequences to get coverage data:
qualimap bamqc -bam $PATH_MAP/${SAMPLE}.mtDNA.mem.merged.sort.rmdup.uniq.bam -nt 2 -outdir $PATH_QUALI/ -outformat "HTML"

#Question 11: What coverage of the mtDNA do you have?
#We have 159X coverage of the mtDNA, which means that every base in the reference sequence has at least one read mapped to it. This is a good result, as it indicates that we have successfully captured the entire mitochondrial genome in our sequencing data.

#Question 12: Choose two other statistics that Qualimap provides and describe them below.
#Mapped Reads: This statistic indicates the percentage of reads that were successfully mapped to the reference genome. A high percentage of mapped reads suggests that the sequencing data is of good quality and that the reference genome is a good match for the sample being analyzed.
#Mismatches and Indels: This statistic provides information about the number of mismatches and insertions/deletions (indels) in the aligned reads compared to the reference genome. A high number of mismatches or indels may indicate sequencing errors, contamination, or differences between the sample and the reference genome. It can also provide insights into the genetic variation present in the sample.
#http://qualimap.conesalab.org/doc_html/index.html