#!/bin/bash -l

##OVERVIEW for WEEK 8 ASSIGNMENT - Mapping to hg19:
#For this assignment, we will be mapping our trimmed sequences to the human reference genomes (hg19), which is a 3-step process:
#1. We first have to do the actual mapping using bwa 
#2. Then we use samtools to filter the mapped reads to a certain quality. We also use samtools to merge reads from multiple lanes or sequencing runs
#3. Finally, we run mapping statistics using qualimap to determine coverage

## This may sound familar; it is the same process as mapping to the hg19 rCRS, but using the whole genome reference (hg19) instead!

#The trimmed sequences should be in your ../Data/2_AdapterRemoval/FINISHED directory
#If you have not trimmed the adapters yet, please go back to Week 3 and/or 4 and run through the assignment there.

#######################
########PART 0########
######################
#housekeeping before we start the assignment!!! Keep a clean house!!!

#copy this script into your own USER directory. Type the following into the terminal:
USER="Lucy" #replace Lucy with your actual foldername
cp /dartfs/rc/lab/F/FleskesR/BioinfoWG/ASSIGNMENTS/WEEK8-MappingHG19/8_MappingHG19_assignment.sh /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Scripts/
#then modify the script in your own folder


######################
########PART 1########
######################

#We will only be running a job script for this lesson, 
#since we are mostly duplicating the steps we ran for mapping to the hg19 reference sequence,
#and because the human genome reference sequence is very large which means mapping can take a long time

##Step 1: set up folders and variables
USER="Lucy" #replace Lucy with your actual foldername
mkdir -p /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/8_MappingHG19/{mapped,qualimap}
ls /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/8_MappingHG19/qualimap

#Step 2: Explore hg19
#Look at the >3 billion base-pairs of the hg19 human genome reference sequence (!!IMPORTANT: DO NOT EDIT THIS FILE!!)
less /dartfs-hpc/rc/home/5/f008715/FleskesR/ReferenceSeqs/hg19/hg19.fa
less /dartfs/rc/lab/F/FleskesR/ReferenceSeqs/MtDNA/rCRS.fasta

##QUESTION 1: How is the hg19.fa file different and similar to the rCRS.fasta file we used for mapping to the hg19 reference?
#The hg19.fa file has extensive strings of Ns in the sequence, which represent unknown bases, while the rCRS.fasta file has bases. Both are fasta files however, the hg19.fa file maps to the chromosomes of the human genome, while the rCRS.fasta file maps to the mitochondrial genome. 

##QUESTION 2: Is there a difference between *.fa and *.fasta file types?
#No, there is no difference between .fa and .fasta file types. They are both fasta files, which are a text-based format for representing nucleotide sequences. The .fa extension is just a shorter version of .fasta, and they can be used interchangeably.

##QUESTION 3: Do some research on hg19. What version of the human reference genome is it? Are there other versions?
#Hg19 stands for "human genome version 19" and is also known as GRCh37. It was released in February 2009 by the Genome Reference Consortium. There are other versions of the human reference genome, including hg18 (GRCh36), hg38 (GRCh38), and more recent updates. Each version may have improvements in terms of accuracy, completeness, and annotation compared to previous versions.

#Step 3: We will want to make a copy of the script we used for hg19 mapping, and rename it:
cd /dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Scripts
cp 5_MappingMTDNA.sh 8_MappingHG19.sh


######################
########PART 2########
######################

#Updating our mapping script 

#While in your Scripts directory, use "code" or "nano" commands to begin editing the new script
code 8_MappingHG19.sh

##ASSIGNMENT: Update your mapping scripts be used for hg19 mapping. Make sure the following has been updated:
#1: Job name

#2: Time duration = 21-01:00:00

#3: Number of cores: --ntasks-per-node=16

#4: Variables and PATHS are correct. (Hint: One correction is for the reference path, which is here: /dartfs/rc/lab/F/FleskesR/ReferenceSeqs/hg19)

#5: All instances of "mtDNA" in file names are replaced with "hg19" (without the quotes) (use Ctl+F (or cmd+F) to find and replace all)

#6: We used the "mem" algorithm for mtDNA; we want to use "aln" for hg19. Replace the full line of bwa aln code with the following two lines (make sure both are indented in by one tab):

bwa aln -t 16 -l 1000 -n 0.01 -o 2 $PATH_REF/hg19.fa $PATH_TRIMMED/${j} > $PATH_MAP/${NAME}.hg19.aln.sai &&
bwa samse $PATH_REF/hg19.fa $PATH_MAP/${NAME}.hg19.aln.sai ${j} > $PATH_MAP/${NAME}.hg19.aln.sam &&

#7: Since we're doing aln, not mem, use Ctl+F (or cmd+F) to find and replace all "mem" instances with "aln" (without the quotes).

#8: We want to make a file of unmapped reads (in case we want to do metagenomics at a later date). We discussed which flag to use in the mtDNA mapping, 
####so add a line of code before "Filtering out mapped reads" that is for "Filtering out Unmapped reads" 
####(Hint: copy and paste the two lines of code from Filtering out mapped reads, change the appropriate flag, and replace "mapped" with "unmapped" (without the quotes) in the file names and echo statement) 


#IMPORTANT: Before submitting, check your script against this one here: /dartfs/rc/lab/F/FleskesR/BioinfoWG/RAW_Scripts/8_MappingHG19.sh


#Now run 8_MappingHG19.sh (make sure you're in your Scripts directory!)
sbatch 8_MappingHG19.sh

#This could take several days. Check on the status:
squeue --me
#Also, check the slurm output file for the job to make sure it is running 
#and not looping back over on samples already run by looking at the "slurm-#######.out" file in your Scripts directory

#QUESTION 4: While this is running, do some research on what the flags we used for bwa aln mean (i.e., bwa aln -t 16 -l 1000 -n 0.01 -o 2),
#and why we use those for aDNA.
#bwa aln: Bwa aln is an algorithm used for aligning short reads to a reference genome. It is designed for high-throughput sequencing data and is particularly effective for aligning reads that are shorter than 100 base pairs, which is common in ancient DNA (aDNA) studies.
#-t 16: Specifies the number of threads to use for the alignment process. In this case, it is set to 16, which allows for faster processing by utilizing multiple CPU cores.
#-l 1000: Specifies the maximum length of the seed to be used for alignment. https://www.sevenbridges.com/short-read-alignment-seeding/
#-n 0.01: Specifies the maximum number of mismatches allowed for a read to be considered a good match. This is set to 0.01, which means that a read can have up to 1% mismatches compared to the reference genome. This is important for aDNA because it often contains damage and degradation, leading to mismatches.
#-o 2: Specifies the maximum number of gap opens allowed per read.
#samse: Bwa samse is a command used to generate a SAM file from the alignment results produced by bwa aln. It takes the output from bwa aln and produces a SAM file that contains the aligned reads and their corresponding information, such as mapping quality and alignment position. This step is necessary to convert the alignment results into a format that can be further processed and analyzed using tools like samtools.

#QUESTION 5: How could we help this script to run faster?
# By increasing the number of threads used for the alignment process (e.g., using -t 32 instead of -t 16), we can speed up the mapping process. 

#Once the job is completed, check the MappingFiltering statistics text file to confirm every sample worked.
#Then, clean up intermediary files and sam files:
USER="Lucy" #replace Lucy with your actual foldername
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/8_MappingHG19/mapped
cd $PATH_MAP

rm -f *.hg19.aln.mapped.q30.sort.rmdup.bam
rm -f *.hg19.aln.mapped.q30.sort.bam
rm -f *.hg19.aln.mapped.q30.bam
rm -f *.hg19.aln.sa*

######################
########PART 3########
######################
#Once mapping is finished, we need to merge the unique sequencing reads into a single file. 
#We will use samtools merge command. Look at the manual to see how the "merge" program works.

#ASSIGNMENT: Make a new job script for merging your samples.
#You will need to make a new .sh shell script,
code 8_MergeHG19.sh 
#include the correct headers, 
#and paste the code between the two "#######################" below after the headers
#MAKE SURE that you update the full file names of your *hg19.aln.mapped.q30.sort.rmdup.uniq.bam files that need to be merged!
#Then save this file as 8_MergeHG19.sh in your Scripts folder
#Hint 1: See /dartfs/rc/lab/F/FleskesR/BioinfoWG/RAW_Scripts/8_MergeHG19.sh to check your work.

#######################

source ~/.bashrc

conda activate Sequencing

##Step 1: set up folders and variables
USER="Lucy" #replace Lucy with your actual foldername
SAMPLE="CAL03"
#change CAL## to your assigned sample

#Make variable for mapped pathss
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/8_MappingHG19/mapped

cd $PATH_MAP

##Step 2: Merge files using samtools
#You will need to change the individual file names after the first line to match your file names. (Leave the first line as it is.)
#Use ls *.uniq.bam to get list of your file names.
#You will also need to add a backslash \ at the end of each line except for the last, 
#and each line after the first needs to be indented by one tab.

samtools merge -@ 16 ${SAMPLE}.hg19.aln.merged.bam \
    CAL05_FGC2096_s_1.R1.trimmed3.fastq.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2096_s_1.R2.trimmed2.fastq.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2098_s_1_CGGCTATG-GGCTCTGA.fastq.truncated.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2098_s_2_CGGCTATG-GGCTCTGA.fastq.truncated.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2098_s_3_CGGCTATG-GGCTCTGA.fastq.truncated.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2098_s_4_CGGCTATG-GGCTCTGA.fastq.truncated.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2099_s_1_CGGCTATG-GGCTCTGA.fastq.truncated.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \
    CAL05_FGC2099_s_2_CGGCTATG-GGCTCTGA.fastq.truncated.hg19.aln.mapped.q30.sort.rmdup.uniq.bam \

##Step 3: Now we remove duplicates and reads that have multiple mappings. First, we sort the reads by leftmost coordinate, then remove duplicates.
#Sorting alignment by leftmost coordinate
samtools sort -T ${SAMPLE}.hg19.aln.merged.sort -o ${SAMPLE}.hg19.aln.merged.sort.bam ${SAMPLE}.hg19.aln.merged.bam
#Removing duplicates
samtools rmdup -s ${SAMPLE}.hg19.aln.merged.sort.bam ${SAMPLE}.hg19.aln.merged.sort.rmdup.bam
#Removing reads with multiple mappings
samtools view -bh -F 0x900 ${SAMPLE}.hg19.aln.merged.sort.rmdup.bam > ${SAMPLE}.hg19.aln.merged.sort.rmdup.uniq.bam

#Finally, we create a new MergingStats file to keep this data:
echo -e "MAKE MERGING FILE"
echo -e "Sample \t Total Merged Reads \t Unique Merged Reads" > $PATH_MAP/MergingFilteringStats_${SAMPLE}_hg19.txt

merged=`samtools view -c $PATH_MAP/${SAMPLE}.hg19.aln.merged.bam`
uniq=`samtools view -c $PATH_MAP/${SAMPLE}.hg19.aln.merged.sort.rmdup.uniq.bam`

echo -e "${SAMPLE} \t $merged \t $uniq " >> $PATH_MAP/MergingFilteringStats_${SAMPLE}_hg19.txt

#######################

#Now run 8_MergeHG19.sh (make sure you're in your Scripts directory!)
sbatch 8_MergeHG19.sh

#This could take several days. Check on the status:
squeue --me
#Also, check the slurm output file for the job to make sure it is running 
#and not looping back over on samples already run by looking at the "slurm-#######.out" file in your Scripts directory

#if you get any errors, then you will need to debug the slurm script and resubmit the job.

##Once the job is done running, clean up intermediary files
rm ${SAMPLE}.hg19.aln.merged.sort.rmdup.bam
rm ${SAMPLE}.hg19.aln.merged.sort.bam

#Question 6: Now how many MERGED unique mapped reads with a quality of at least 30 do we have? 
#36287298 unique merged reads

######################
########PART 4########
######################
#Now that we have our final merged, unique reads mapped to the human hg19 sequence, 
#We run statistics to get the coverage

#We start an interactive session as before:
srun --pty bash -l
#Then activate the conda environment for mapping
conda activate Sequencing

#Set up variables
USER="Lucy" #replace Lucy with your actual foldername
SAMPLE="CAL03" #replace CAL## with your assigned sample
PATH_MAP=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/8_MappingHG19/mapped
PATH_QUALI=/dartfs/rc/lab/F/FleskesR/BioinfoWG/USERS/${USER}/Data/8_MappingHG19/qualimap

#Run Qualimap on the merged sequences to get coverage data:
qualimap bamqc -bam $PATH_MAP/${SAMPLE}.hg19.aln.merged.sort.rmdup.uniq.bam -nt 2 -outdir $PATH_QUALI/ -outformat "HTML"

conda deactivate
#Question 7: What coverage of the hg19 do you have?
#There is 0.7684X coverage of the hg19 reference genome, which means that 76.84% of the bases in the reference genome have at least one read mapped to them.

#Question 8: Choose two other statistics that Qualimap provides and describe them below.
#Homopolymer Indels: This statistic provides information about the number of insertions and deletions (indels) that occur in homopolymer regions, which are stretches of DNA where the same nucleotide is repeated multiple times (e.g., AAAAA). Homopolymer indels can be a common source of sequencing errors, especially in ancient DNA, so this statistic can help assess the quality of the sequencing data.
#Mean Mapping Quality: This statistic provides the average mapping quality score for the aligned reads. The mapping quality score is a measure of how confidently a read is mapped to a particular location in the reference genome. A higher mean mapping quality indicates that the reads are more reliably mapped, which can be important for downstream analyses such as variant calling or population genetics studies.